descriptor-schema-version: "2.2"

info:
    name: "iotsgwapp"
    description: "IoT Smart Gateway IOx application"
    version: "2.0"
    author-link: "https://softserveinc.com"
    author-name: "SoftServe"
    
app:
    cpuarch: x86_64
    type: docker
    resources:
        profile: c1.tiny
        network:
            -
                interface-name: eth1
    startup:
        rootfs: rootfs.tar
        target: ["./IoT-Smart-Gateway"]